# Django

# Enable Django's builtin admin interface
ADMIN_ENABLED = True
DEBUG = True
ALLOWED_HOSTS = []

# SocialAuth general
SOCIAL_AUTH_REDIRECT_IS_HTTPS = False

# Github OAuth2
SOCIAL_AUTH_GITHUB_KEY = ''
SOCIAL_AUTH_GITHUB_SECRET = ''

# Google OAuth2
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = ''
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = ''

# Microsoft / Live
SOCIAL_AUTH_LIVE_KEY = ''
SOCIAL_AUTH_LIVE_SECRET = ''

# Yahoo OAuth2
SOCIAL_AUTH_YAHOO_OAUTH2_KEY = ''
SOCIAL_AUTH_YAHOO_OAUTH2_SECRET = ''
